name: CI / Docker - Build Image

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches: [ "master", "*" ]
  pull_request:
    branches: [ "master", "*" ]
  workflow_dispatch:

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
