name: CI / Gitlab - Mirror Sync

on:
  schedule:
    - cron: '0 */2 * * *'
  push: 
    branches: ["*"]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Gitlab Repo Sync
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Git Repo
      uses: actions/cache@v4
      with:
        path: |
          ~/.git
          .git
        key: ${{ runner.os }}-git-${{ github.sha }}
        
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ secrets.TARGET_URL }}
        target-username: ${{ secrets.TARGET_USERNAME }}
        target-token: ${{ secrets.TARGET_TOKEN }}